# Generated by Django 4.2.4 on 2023-09-02 06:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board_app', '0003_alter_post_text'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='text',
            new_name='content',
        ),
    ]
